version: "3.7"
services:   
  bookshop-spring:
    container_name: bookshop_spring
    image: bookshop-spring
    restart: always
    ports:
      - 8443:8443
    networks:
      - nginx
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db   
  db:
    container_name: db
    restart: always
    image: mysql
    networks:
      - nginx
    healthcheck:
     test: "/usr/bin/mysql --user=root --password=mysql --execute \"SHOW DATABASES;\""
     interval: 2s
     timeout: 20s
     retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db_bookshop
      - MYSQL_ROOT_HOST=127.0.0.1
    command: --secure-file-priv=images

    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/images:/images
      - ./db/init:/docker-entrypoint-initdb.d/init:ro
      
  bookshop-react:
    image: bookshop-react       
    container_name: bookshop_react
    restart: always
    networks:
      - nginx
      
  portfolio:
    container_name:  portfolio_react
    image: portfolio
    restart: always
    networks:
      - nginx
      
  gateway:
    image: gateway
    container_name: gateway
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    depends_on:
      - portfolio
      - bookshop-react
      - bookshop-spring
    volumes:
      - ./byousefi/ssl:/etc/ssl
      

networks:
  nginx:
